### ISSUE TITLE
About training!!!

### ISSUE THREAD

**Issue by Maikuraky** [gjoni/trRosetta#9]
Hi, Ivan
Can you relax the training code which contains data processing such as subsample and 300 residues limit?
This confuse me a long time.
Thanks!

**Comment by gjoni** [comment]
Hi Maikuraky,
There were two main reasons for doing msa subsampling and slicing: msa subsampling is a simple data diversification techniques and using it gives a better model compared to not using, while slicing is used for technical reasons and helps to fit into the gpu memory (otherwise we get OOMs caused by long sequences).

Ivan

**Comment by gjoni** [comment]
closed
